#!/bin/bash
set -Eeuo pipefail
# Reference: https://github.com/probonopd/ippsample/blob/75ecdb4d7e88468eb3c631dda1c43dbfe142f8e8/appimage/AppRun

HERE="$(dirname "$(readlink -f "${0}")")"

__HELP_HEADER="QEMU Multicall Binary

Usage: $(basename ${ARGV0}) APP [OPTIONS] 

Apps available:"

help() {
  >&2 echo "$__HELP_HEADER"
  for f in "${HERE}/usr/bin/"*; do
    >&2 echo -e "\t$(basename ${f})"
  done
}

if [ ! -z $APPIMAGE ] ; then # script is executed by AppImage runtime
  
  BINARY_NAME=$(basename "$ARGV0")
  if [ -e "${HERE}/usr/bin/${BINARY_NAME}" ] ; then
    exec "${HERE}/usr/bin/${BINARY_NAME}" "$@"
  else
    if [ $# -ge 1 ] && [ -n "$1" ]; then # try the first argument 
      BINARY_NAME="${1}"
      shift
      if [ -e "${HERE}/usr/bin/${BINARY_NAME}" ] ; then
        exec "${HERE}/usr/bin/${BINARY_NAME}" "$@"
      fi
    fi # end try the first argument 
  fi # end try the symlinked name
fi

help
exit -1
