#!/bin/bash
set -Eeuo pipefail
# Reference: https://github.com/probonopd/ippsample/blob/75ecdb4d7e88468eb3c631dda1c43dbfe142f8e8/appimage/AppRun

HERE="$(dirname "$(readlink -f "${0}")")"

__HELP_HEADER="
QEMU Multicall Binary

Usage: $(basename ${0}) APP [OPTIONS] 

Apps:
"

help() {
  >&2 echo "$__HELP_HEADER"
  for f in "${HERE}/usr/bin/"*; do
    >&2 echo "\t$(basename ${f})"
  done
}

if [ ! -z $APPIMAGE ] ; then
  # first try the symlinked name
  BINARY_NAME=$(basename "$ARGV0")
  if [ -e "${HERE}/usr/bin/$BINARY_NAME" ] ; then
    exec "${HERE}/usr/bin/$BINARY_NAME" "$@"
  else
    # then try the first argument
    BINARY_NAME="${1}"
    shift
    if [ -e "${HERE}/usr/bin/$BINARY_NAME" ] ; then
      exec "${HERE}/usr/bin/$BINARY_NAME" "$@"
    else
      help
    fi
  fi
else
  # script executed directly outside the AppImage runtime
  help
fi
